### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by blg002** [h5bp/Front-end-Developer-Interview-Questions#11]
It would be cool to have links to resources explaining the answers to some of the questions.

**Comment by collegeimprovements** [comment]
Please provide general answers. It would be a great help. But at the same time it would be a lot of work. I would be glad if I can help here.

**Comment by brunobasto** [comment]
I also agree that at least some guidance to finding the answers would be good. May be links to specs, w3schools or whatever..

**Comment by bengrunfeld** [comment]
Here's a short blog post I wrote with answers to some of the questions. Use at your own risk.
[http://cloudandcode.tumblr.com/post/100844594181/front-end-developer-interview-questions](http://cloudandcode.tumblr.com/post/100844594181/front-end-developer-interview-questions)

**Comment by darcyclarke** [comment]
@bengrunfeld I generally look down on this practice and don't want to promote people posting "answers" to this repo or even in issues. Please refer to [my comment](https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/215#issuecomment-68835978) on issue #215 if that's not clear.

**Comment by bengrunfeld** [comment]
Cool, I'll remove it.

**Comment by degouville** [comment]
Thanks now we can copy paste to ChatGPT and Claude.ai 😉 and then this repo is finally useful...
