### ISSUE TITLE
Include question regarding difference between CSS and CSS3

### ISSUE THREAD

**Issue by santup** [h5bp/Front-end-Developer-Interview-Questions#186]

**Comment by darcyclarke** [comment]
I think there's a few people who would take issue with us trying to define a difference. CSS3 saw a modularization of all the specs which fragmented versioning, so there won't be a formal CSS4 (so numbers aren't a big deal anymore: http://en.wikipedia.org/wiki/Cascading_Style_Sheets#CSS_4). But yea... I think we should probably stop referencing things like HTML**5** and CSS**3** in things.
