### ISSUE TITLE
Add 1 general question

### ISSUE THREAD

**Issue by m-bodmer** [h5bp/Front-end-Developer-Interview-Questions#221]
#### General Question
What is a recent technical challenge you experienced and how did you solve it?

**Comment by richgilbank** [comment]
Hey Marc, thanks for the question! 100% agree this is a worthwhile question, mind submitting a PR? 
PS, swing by Shopify sometime, would love to show you around the new space!

**Comment by appleboy** [comment]
Closed via #222
