### ISSUE TITLE
`GET` and `POST` question under HTML section seems misplaced.

### ISSUE THREAD

**Issue by GeorgeMac** [h5bp/Front-end-Developer-Interview-Questions#227]
I would argue this has nothing to do with HTML. Its a HTTP question. Perhaps it belongs under general?

**Comment by richgilbank** [comment]
Fair enough. I think we might even have enough questions to make a new section, something along the lines of `HTTP`, covering GET/POST, headers, MIME types, etc. Thoughts?

**Comment by GeorgeMac** [comment]
Yeah a HTTP section sounds more fitting :)

**Comment by jlmitch5** [comment]
+1.  You could include REST vs. SOAP in there too.
