### ISSUE TITLE
Spell "lasagna" so the palindrome works

### ISSUE THREAD

**Issue by patik** [h5bp/Front-end-Developer-Interview-Questions#229]
```js
"i'm a lasagne hog".split("").reverse().join("");
```

"Lasagna" ends with an 'a'. Then it works as a palindrome: "Go hang a salami, I'm a lasagna hog". With the current spelling it's just "go heng a salami" which doesn't sound as fun.

**Comment by richgilbank** [comment]
Closed by https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/228
