### ISSUE TITLE
Add questions on AngularJS/EmberJS or generic client side MV* frameworks..

### ISSUE THREAD

**Issue by mappmechanic** [h5bp/Front-end-Developer-Interview-Questions#231]
These days most Front Ends use a MV* framework and hence it is important for your list of questions to have some on this topic too.

**Comment by richgilbank** [comment]
This has been discussed in many issues and PRs in the past, the outcome of which has always been that it's not a fundamental requirement to front-end development. As such, there's no plans of yet to add questions for all the MV*s.
