### ISSUE TITLE
Spelling error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dastagg** [h5bp/Front-end-Developer-Interview-Questions#235]
Please do not open issues or pull requests that invlove including answers to any of the questions.

Change to:
Please do not open issues or pull requests that involve including answers to any of the questions.

Also:

IMPORTANT: By submitting pathes, you agree to allow the project owners to license your

Change to:
IMPORTANT: By submitting patches, you agree to allow the project owners to license your

**Comment by appleboy** [comment]
Closed via #236
