### ISSUE TITLE
Remove hints/examples from the questions

### ISSUE THREAD

**Issue by phanan** [h5bp/Front-end-Developer-Interview-Questions#247]
Several questions have hints/examples following them:

> Talk about your preferred development environment. _(OS, Editor or IDE, Browsers, Tools, etc.)_

> What are the advantages/disadvantages of using CSS preprocessors? _(Sass, Compass, Stylus, LESS)_

> What existing CSS frameworks have you used locally, or in production? _(Bootstrap, PureCSS, Foundation etc.)_

> Have you ever used JavaScript templating?
> If so, what libraries have you used? _(Mustache.js, Handlebars etc.)_

IMHO these are redundant. For a certain, an interviewer doesn't need them. A good candidate wouldn't need them, either. So why are they even here?

**Comment by phanan** [comment]
Ping

**Comment by appleboy** [comment]
Closed via a300b72fa3e945f1caf1d961d6de8f5040edbbd7
