### ISSUE TITLE
Weird question

### ISSUE THREAD

**Issue by phanan** [h5bp/Front-end-Developer-Interview-Questions#249]
So in the CSS section, there's this standalone question:

> CSS property hacks, conditionally included .css files, or... something else?

What exactly is this question asking? Sorry I couldn't trace back to its origin.

**Comment by darcyclarke** [comment]
`property hacks` http://browserhacks.com/
`conditionally included .css files` http://www.quirksmode.org/css/condcom.html
`or... something else` write good, standards-based CSS?

As an aside, I do think this question is on the weaker side. What's the point of it? I guess it's trying to see how a user approaches browser-specific bugs in CSS. The `or... something else` component of the question may allow someone to talk about **feature detection** or maybe **user agent strings** or anything that would give them context that they could develop solutions for whatever problems they're having.

**Comment by phanan** [comment]
> I guess it's trying to see how a user approaches browser-specific bugs in CSS

Then shouldn't it be something like:

> Do you use CSS property hacks, conditionally included CSS tyles, or any other solutions to approach browser-specific issues?

Though far from perfect, at least it _looks_ more like a question to me.

**Comment by f3liperamos** [comment]
> Do you use CSS property hacks, conditionally included CSS tyles, or any other solutions to approach browser-specific issues?

Seems more like a question now. More accurate. +1
If everyone agrees and you didn't do it yet in your branch, I can do that.

**Comment by phanan** [comment]
I'm all for it, but would like to change `property hacks` into `selector hacks` or just `hacks` following @darcyclarke's suggestion.

**Comment by darcyclarke** [comment]
I think that all of these topics are actually answers to the question of "what is your approach?". Right now the phrasing makes it seem like a multiple choice question (which isn't good). We should always strive for open-ended questions and phrasing; So, my suggestion for a revision is below:

> How would you approach fixing browser-specific styling issues?

Then someone could respond by referencing `selector hacks`, `property hacks`, `conditional includes` or some `other approach`. This way we don't give away or allude to any preference in approach to begin with.

**Comment by phanan** [comment]
Agreed, so could you update it then? Must be faster than us creating a branch, send PR and all.
