### ISSUE TITLE
Break up JS questions

### ISSUE THREAD

**Issue by richgilbank** [h5bp/Front-end-Developer-Interview-Questions#257]
The JS Questions section is getting pretty large - I'd be inclined to break it into two smaller sections: `JS language questions` and `JS usage questions`, or `JS implementation questions`...or something. As an example, a question like `Explain how 'this' works in JavaScript` would be clearly a language-specific question, while the fizzbuzz question would be about implementation. Just throwing this out there. 
Thoughts?

**Comment by appleboy** [comment]
Agree @richgilbank :+1:

**Comment by phanan** [comment]
Or, is it a potential to break each section into a file instead? Just my $0.02.

**Comment by matachines** [comment]
Agreed, especially when there are questions about the language and also questions related libraries/utilities (do you use templating/AMD vs Common) mixed together. It might be helpful for someone who just wants to master the language to have them separated!

**Comment by TheDerek** [comment]
Do interviewers really ask questions about what happens if you abuse Javascript? What's the point since you shouldn't be using it in that manner in production anyway.

**Comment by darcyclarke** [comment]
@TheDerek I'm not sure what you're referring to but your feedback sounds a bit off-topic (unless someone has removed the comment you were replying to).

-----

@matachines We won't be including any library-specific content in the future. Native implementations and general concepts, patterns and architecture questions are different.

-----

@phanan I think there will always be ways to improve navigation, as we grow bigger, but my hope is that we'll maintain a single file. 

-----

@richgilbank I agree. With *30+* questions, that section does seem a bit `.length`y :wink: Although, the **CSS** section isn't too far behind, so we may need to consider it as well (or *very* soon). 

**Initial Feedback:**
The terms `language`, `usage` and `implementation` don't sound succinct enough to me. `Usage` and `implementation`, specifically, sound like the same topic/too similar. That said, I may need to see the division, as you have it in mind, to appreciate the different correlations and what will go where. It may make sense to start a Pull Request now with the changes you think work and we can discuss the verbage and categorization more there.

**Alternative Suggestion:**
I had once thought of splitting up all the sections into context-specific sub-categories like: `What`, `Where`, `When`, `Why`, `How` and `Explain`. Most questions fit nicely into these categories already and this approach would help guide phrasing for future additions (ie. someone would know exactly `what` goes `where`). It definitely has the potential to add a lot of sub-categories and spreading out content but it's just a thought. 

I'm definitely open to any other suggestions in terms of sub-categorization. A simple reorg, grouping similar questions/phrasing, might also help with discovery.

**Comment by marlun78** [comment]
I think it would make a lot of sense split JavaScript Language question and DOM questions. A new section for ES2015/16 features would also be nice.

**Comment by diessica** [comment]
@marlun78 I don't believe it's necessary to add ES6 questions. Creativity from the candidate should be expected instead (you can solve problems like the fizzbuzz one with ES6, for example. It's a beautiful solution with ES6 btw, it'd be lovely to see the candidate use it alone).

**Comment by roblarsen** [comment]
This is captured in #435
