### ISSUE TITLE
Join us on The Changelog (today?)

### ISSUE THREAD

**Issue by adamstac** [h5bp/Front-end-Developer-Interview-Questions#258]
Howdy from The Changelog!

Sorry for a last minute ask, but @darcyclarke any chance you'd be open to come on The Changelog today at 3pm CT via Skype to talk about this project?

We had a last minute guest cancellation for today's show, and we were already linking this project up in [the next issue of Weekly](http://thechangelog.com/weekly/) that ships tomorrow -- so we thought, why not get them on the podcast!

You might have heard of our show, but if not -- The Changelog is a podcast covering what's fresh and new in open source. Listen to the show here http://thechangelog.com/podcast/ or here http://5by5.tv/changelog

Looking forward to talking to ya!

Adam, EIC

**Comment by darcyclarke** [comment]
I'm game. Shot you a quick Tweet and we should connect through email for more info. I've definitely heard of the podcast. Going to close this though, as it's not technically an issue. We'll chat more today I'm sure. Cheers!
