### ISSUE TITLE
Use of semi-obscure acronyms, question phrasing

### ISSUE THREAD

**Issue by pnevares** [h5bp/Front-end-Developer-Interview-Questions#266]
Most acronyms in the document should be painfully obvious to developers with relevant experience but a few stood to me as relatively obscure. The concepts might be well known, but not the jargon. Could these be de-acronymized?

* FOUC
* DNT
* SSE

These entries also seemed out of place:

*Write a simple slideshow page*
A coding sample has a place in an interview, but not in these questions. Could this be "Describe how you would create a simple slideshow page"?

*AMD vs. CommonJS?*
Is this asking for personal preference, or a comparison of these projects' features and direction? "What do you think of AMD vs CommonJS?"

Thanks for your time!

**Comment by richgilbank** [comment]
I'm not opposed to it, particularly for the latter two (DNT and SSE), as some front-end focused devs may not have ever worked directly with them before. 

I 100% agree about `Write a simple slideshow page`. It's not a question, and a list of _Front end Developer Interview Tasks_ could be an entirely separate project :smirk:

:+1: on the module loader question too. 

I guess what I'm trying to say is, yes. Yes to all the things! Feel free to submit a PR, I'd be happy to give it my approval.
