### ISSUE TITLE
Assign a section code for each question and use section sign (§) 

### ISSUE THREAD

**Issue by mohsen1** [h5bp/Front-end-Developer-Interview-Questions#272]
This will help with translation not falling behind or if they fell behind it's easy to track which questions are missing or modified.

Like official documents assign a section code to each question and indicate that code after each question .

Foe example:

```
#### General Questions (§ 1):

* What did you learn yesterday/this week? (§ 1.1)
* What excites or interests you about coding? (§ 1.2)
```

```
```

**Comment by darcyclarke** [comment]
Thanks @mohsen1! We're mulling over some ideas on how to fix this and I think sections codes will definitely help although we need to be concerned about the potential deletion and reordering of questions as well. I think some kind of unique id will have to be used to maintain the most accuracy and sanity going forward.

**Comment by darcyclarke** [comment]
Some work has been done on this in a feature branch which would also generate the website: https://github.com/h5bp/Front-end-Developer-Interview-Questions/blob/feature/build-website/questions.yaml

**Comment by roblarsen** [comment]
No longer relevant
