### ISSUE TITLE
史上最全 前端开发面试问题及答案整理

### ISSUE THREAD

**Issue by hawx1993** [h5bp/Front-end-Developer-Interview-Questions#273]
https://github.com/hawx1993/Front-end-Interview-questions

**Comment by appleboy** [comment]
Thanks for your information but we are talk in English here.

**Comment by brunobasto** [comment]
Can't it go to the translations folder? Seems he had a lot of work translating all this...

**Comment by phanan** [comment]
It's not a translation is it?

**Comment by brunobasto** [comment]
Oh, right! I guess it isn't. Brain farted ;p

**Comment by penJunTan** [comment]
你好 @appleboy 先问问, 没有冒犯之意, 你应该能认识中文吧? ( hi, can you read chinese? if not, skip this comment )
@hawx1993 收集整理前端面试题列, 我认为其中有些条目, 如 iframe 使用场景优劣性, js 深度拷贝等, 可适合 PR. 你能帮忙做一下吗? 或是由 @hawx1993 来做?

**Comment by appleboy** [comment]
@penJunTan 

如果要增加面試題目，請直接發 PR，大家可以一起討論，是否加入官方的 Readme，這部份就由 @hawx1993 來決定哪些題目適合放入官方 Repo，這邊需要大家審核才可以放入，不是我一個人可以決定的。

**Comment by anonmily** [comment]
好像這個PR是有問題的答案吧（應該是吧？）。其實我也是覺得有一個有答案的文件會很有用呢⋯好像我們目前為止是沒有吧（英文版）？

Seems like this PR has answers to the questions? (Should be, I think?) Actually, I also feel like having a document with some of the answers might be useful...I don't think we have any up until now right (an English version)?
