### ISSUE TITLE
Translating into a right to left language

### ISSUE THREAD

**Issue by omidfi** [h5bp/Front-end-Developer-Interview-Questions#274]
Hi, I was thinking of translating this into Farsi/Persian. It's a right to left language like Arabic.
It will be readable on github anyway, but not looking nice. Any experience with that?

**Comment by alrra** [comment]
> It's a right to left language like Arabic. It will be readable on github anyway, but not looking nice. Any experience with that? 

@omidfi Just add `<div dir="rtl" lang="fa">` at the beginning of the `README.md` file.

**Comment by omidfi** [comment]
ok thanks
