### ISSUE TITLE
master README out of sync with gh-pages index.html

### ISSUE THREAD

**Issue by cch5ng** [h5bp/Front-end-Developer-Interview-Questions#277]
hi, I've been looking at both lists of questions and it seems like the contents are out of sync. for ex. the master README contains network questions but doesn't contain a jQuery section. the index.html page (http://h5bp.github.io/Front-end-Developer-Interview-Questions/) contains a jQuery section but no network section. thanks.

**Comment by arthurvr** [comment]
@cch5ng Thanks for letting us know, it's outdated indeed. The team is working on a better system: https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/269.

@darcyclarke If you have five minutes, can you update the branch for now?

**Comment by darcyclarke** [comment]
**Update**: http://h5bp.github.io/Front-end-Developer-Interview-Questions/
