### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by marcobiedermann** [h5bp/Front-end-Developer-Interview-Questions#279]
Maybe we could expand this question. There are more ways how to do animations on the web.
What do you guys think about this?
If you agree, I could send you a pull-request :)

> Explain some of the pros and cons for CSS animations versus JavaScript animations.

Animations: CSS, JavaScript, SVG, Canvas or Flash. When to use which and what are some of the pros and cons of each.

**Comment by darcyclarke** [comment]
Some quick notes:
- Canvas animations are controlled by JavaScript
- Opinion: SVG animations are often controlled by JavaScript
- Opinion: Flash is no longer relevant for UI/animations

I think what this question alludes to, right now, is a level of control over animation (ie. if/how you are able to start, stop, pause or reverse) and less about the contents being animated (ie. DOM elements). I also don't see much of a difference between CSS vs. SVG animations unless you start to incorporate manipulation of objects (ie. vector shapes/paths), but again, that deals more with the contents.

I think it may get a bit confusing if we try to differentiate between a JavaScript and a Canvas or SVG animation. Not sure where we should land here.

**Comment by roblarsen** [comment]
Tidying, making this 🏚️ into 🏡

Happy to revisit!
