### ISSUE TITLE
Load content

### ISSUE THREAD

**Issue by marcobiedermann** [h5bp/Front-end-Developer-Interview-Questions#280]
Explain the differences between AJAX, iFrame and Frameset. How do they differentiate?

**Comment by darcyclarke** [comment]
What is the purpose of this question? Like, what kind of knowledge are you hoping to ascertain from this line of questioning? As a potential candidate, the word `content` is very vague. Maybe try thinking about how you'd answer this and rephrase the question.

**Comment by marcobiedermann** [comment]
@darcyclarke Maybe you could come up with a better question. Sorry a am not a native speaker.
I mean, how to load in content? Use an iframe for this? Load it via ajax? What are the differences? The are the pros and cons of each technique. When to use what? Which one is better for SEO?
Something like that.

**Comment by nhz-io** [comment]
Omg, frameset? really? lets go gopher then if we go so far

**Comment by roblarsen** [comment]
👍 for the gopher reference.
