### ISSUE TITLE
JavaScript Design Pattern

### ISSUE THREAD

**Issue by marcobiedermann** [h5bp/Front-end-Developer-Interview-Questions#281]
JS Questions:
Do you have any experience with some Design Pattern? What are the purpose of pattern in programming languages?

**Comment by darcyclarke** [comment]
I think a JavaScript/programming design patterns question would be good to have but I think you have to be a bit more clear with your phrasing. Example:

> Do you have any experience with JavaScript design patterns? If so, could you name the ones you've worked with or implemented?

**Comment by marcobiedermann** [comment]
@darcyclarke Good point. But I would add, the question what is the purpose of it. Why this is important and what are the benefits of it.

**Comment by arthurvr** [comment]
I definitely agree that we should have a question about this. A PR would probably help to push this forward :)

**Comment by yichenlivened** [comment]
I found this free course in Udacity is very helpful. [Javascript design patterns](https://classroom.udacity.com/courses/ud989)

**Comment by cezaraugusto** [comment]
+1 from me too, please open a PR if you have something in mind, for now closing as stale. thanks!
