### ISSUE TITLE
Where are the answers? 

### ISSUE THREAD

**Issue by youssefdetovernickr** [h5bp/Front-end-Developer-Interview-Questions#300]
As a person who wants to learn using these questions, is there a page with the answers somewhere too? (for the factual questions)

**Comment by arthurvr** [comment]
Duplicate of https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/11. I'm personally :-1: but leaving this open for the team if they'd like to reconsider it.

**Comment by darcyclarke** [comment]
Please read our [Contributing.md](https://github.com/h5bp/Front-end-Developer-Interview-Questions/blob/master/CONTRIBUTING.md#using-the-issue-tracker) and, for more insight, I've written about this before on other issues/pull-requests like https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/215#issuecomment-68835978
