### ISSUE TITLE
http status code

### ISSUE THREAD

**Issue by kinglerzou** [h5bp/Front-end-Developer-Interview-Questions#304]
write the status code you kown and describe them;
when you answer 304,you will be asked the remark about cache such as cache-control,expire,last-modifed,etag and so on.

**Comment by arthurvr** [comment]
I wonder how in-depth we should go in here, though I think a basic knowledge of these things can be useful (even if it's just to deal with Ajax).

**Comment by darcyclarke** [comment]
A simple Google search gives you all the http status code information you'll need to know. I asking a candidate to list off the http status codes they remember, and their usages, is kind of like asking someone to be a human dictionary. I'd much ask a broader question about caching (if that's the real objective) and see if the candidate brings up cache-control, expire headers and the 304 http status code as a result of their solution to a problem.

**Comment by raymatos** [comment]
A good question I ask is "if given the task to performance test a web app, what would you look for?"  This question leads into cache control, caching mechanisms, browser layouts and repaints, js memory, garbage collection, etc.  



—

**Comment by strugee** [comment]
> "if given the task to performance test a web app, what would you look for?"

This is pretty good, but seems like we could make it better, e.g. by specifying a context. On mobile network requests will have a lot more impact, for example, so you might want to focus on very aggressive caching. Or you could specify "x feels sluggish; where do you begin?". If "x" was e.g. an animation, you might profile the JS, and if it was something taking a really long time to load, you might look at caching.

**Comment by roblarsen** [comment]
[418 I'm a teapot \- HTTP \| MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418)
