### ISSUE TITLE
Transpilers question

### ISSUE THREAD

**Issue by nhz-io** [h5bp/Front-end-Developer-Interview-Questions#307]
Imho, should ask about familiarity with transpilers (coffeescript, iced coffee, livescript, typescript)

**Comment by lsd** [comment]
What would this reveal about a candidate? Hardly anything, and these are things you learn in the field.

**Comment by raymatos** [comment]
And transpilers doesn't always mean they know the underlying language. 



—

**Comment by darcyclarke** [comment]
I'm not opposed asking a candidate if they use transpilers, and which ones, but I would be against asking language-specific implementation details and compilation nuances (just like I would be with frameworks and libraries). This is essentially why we got rid of the original "jQuery-specific" section a long time ago. If you'd like to add a question with something like:

> Do you use transpilers? If so, which ones do you use and why?

I'm sure we'd consider it.

**Comment by arthurvr** [comment]
> I'm not opposed asking a candidate if they use transpilers, and which ones, but I would be against asking language-specific implementation details and compilation nuances (just like I would be with frameworks and libraries).

Agreed. IMHO It makes sense to ask about ES6 to ES5 transpiling specifically though. It's just JavaScript.

**Comment by roblarsen** [comment]
referenced in #435
