### ISSUE TITLE
HTTP Actions

### ISSUE THREAD

**Issue by ajbonner** [h5bp/Front-end-Developer-Interview-Questions#331]
I hope to just be embarrassed here (then I will have learned something!:)), but for the life of me I couldn't figure out what 'HTTP Actions' are?

This is in reference the network questions and specifically 'What are HTTP actions? List all HTTP actions that you know, and explain them.'.

I assume this is to be HTTP _methods_, GET, POST, PATCH, PUT etc? 

If this is the case, why was the term 'HTTP Actions' used, and is this a commonly used term? I googled like heck and there's very little specifically relating to this term, and what little there is is actually regarding HTTP methods.

If this is a question trying to elicit discussion about HTTP verbs, then perhaps the question could be a little bit clearer?

**Comment by phanan** [comment]
Hmm, I guess you have a point there. While it _may_ sound right, "HTTP actions" is not what they're called – it's either _methods_ or _verbs_, from what I know.

**Comment by ajbonner** [comment]
Thanks, I was scratching my head for a good 30 minutes trying to figure out what was meant there, glad to see it *was* about methods/verbs! :)

**Comment by ZengXiong** [comment]
Thanks,I was scratching my head for a good 30 minutes trying to figure out what was meant there, glad to see it was about methods/verbs! :)

**Comment by strugee** [comment]
Fixed a while ago in #314
