### ISSUE TITLE
Some logical reasoning questions or puzzles

### ISSUE THREAD

**Issue by Victoor** [h5bp/Front-end-Developer-Interview-Questions#335]
What do you think? Here it's a list with some examples:

https://www.quora.com/What-are-some-of-the-best-logical-reasoning-questions-or-puzzles-that-you-have-been-asked-in-an-interview

**Comment by ManojAMK** [comment]
That is a good find but I think this repository should be limited to only Front end Developer questions. But a mention of this wouldn't be bad ;)

**Comment by hozefaj** [comment]
For list of problems [leetcode](https://leetcode.com/problemset/algorithms/) is one the best sites, I have come across.

**Comment by roblarsen** [comment]
All those years ago!

**Comment by iamuncommon** [comment]
"{\n  \"Balance\": {\n    \"AllTimeCashedOutStars\": 0,\n    \"AllTimeStars\": 0,\n    \"Coins\": 0,\n    \"Stars\": 0\n  },\n  \"Blocked\": [\n\n  ],\n  \"Channels\": [\n\n  ],\n  \"ExternalIDs\": [\n    {\n      \"LoginId\": {\n        \"DisplayName\": \"britton_ryan\",\n        \"Email\": \"\",\n        \"ExternalId\": \"1265835180419399680\",\n        \"Primary\": true\n      },\n      \"SocialNetwork\": \"TWITTER\"\n    }\n  ],\n  \"Followers\": null,\n  \"Following\": null,\n  \"Groups\": [\n\n  ],\n  \"GuestBroadcasts\": [\n\n  ],\n  \"Installations\": [\n\n  ],\n  \"PeriscopeBroadcasts\": [\n\n  ],\n  \"PeriscopeWatchedBroadcasts\": [\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1eaKbQWBRwrxX\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-30T21:16:30.582258596Z\",\n        \"UserAgent\": \"com.atebits.Tweetie2/8.19 iOS/13.3.1 (Apple;iPhone11,8)\",\n        \"WatchTime\": 590644392880\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1eaKbQWBRwrxX\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-30T21:36:47.064590616Z\",\n        \"UserAgent\": \"com.atebits.Tweetie2/8.19 iOS/13.3.1 (Apple;iPhone11,8)\",\n        \"WatchTime\": 11727063658\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1eaKbQWBRwrxX\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-30T21:47:25.968678765Z\",\n        \"UserAgent\": \"com.atebits.Tweetie2/8.19 iOS/13.3.1 (Apple;iPhone11,8)\",\n        \"WatchTime\": 1475424817\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1eaKbQWBRwrxX\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-30T21:47:28.703124704Z\",\n        \"UserAgent\": \"com.atebits.Tweetie2/8.19 iOS/13.3.1 (Apple;iPhone11,8)\",\n        \"WatchTime\": 973012154\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1ypJdQpZQAYxW\",\n        \"BroadcasterId\": \"1oNQlLnNgXkQw\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:04:06.851543601Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 11570792309\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1ypJdQpZQAYxW\",\n        \"BroadcasterId\": \"1oNQlLnNgXkQw\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:11:28.879182734Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 29713472346\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1ypJdQpZQAYxW\",\n        \"BroadcasterId\": \"1oNQlLnNgXkQw\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:15:48.557207414Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 14195710144\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OdKrqDpWQnxX\",\n        \"BroadcasterId\": \"1WgKgDZoYBXjv\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-31T13:15:54.421335596Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 29191429722\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OdKrqDpWQnxX\",\n        \"BroadcasterId\": \"1WgKgDZoYBXjv\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-31T13:17:36.646069439Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 6701038572\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OyKAYLEXQLKb\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T00:04:58.475504067Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 3937927744\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1vOxwoXralLxB\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T15:24:56.544898241Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 6491585108\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1vOxwoXralLxB\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T15:25:57.346662166Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5539757700\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1vOxwoXrEQrxB\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T15:42:09.268789215Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7220447531\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1MnGnQwDejjKO\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T15:44:01.244349668Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 17658288361\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1MnGnQwDejjKO\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-01T15:44:16.102472868Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 8555055891\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1BdxYQZzZQExX\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T17:02:51.638272456Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7645292046\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1BdxYQZzZQExX\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T17:28:38.944856172Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7172683244\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1vAxRBQdRXqxl\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-03T21:14:09.181878015Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 4857001577\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1gqGvEaAdvgKB\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-03T21:44:33.70261825Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7935096771\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1gqGvEaAdvgKB\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-03T21:44:57.354064794Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5888478560\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1dRKZQZkqgbxB\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-04T20:51:08.70487025Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 4573938157\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1DXxyAmzBmYxM\",\n        \"BroadcasterId\": \"1zYKbGwnrzBje\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-07T00:08:16.835469131Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 4823768561\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1yNGaBamjzdJj\",\n        \"BroadcasterId\": \"1oNQlLnNgXkQw\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-08T14:46:11.431255811Z\",\n        \"UserAgent\": \"Twitter/8.21 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 10530951725\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1lDGLyvkMnPJm\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-08T16:04:12.572989911Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7691275796\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1YpKkQlZpkmJj\",\n        \"BroadcasterId\": \"1zYKbGwnrzBje\",\n        \"NComments\": 0,\n        \"NHearts\": 3,\n        \"Start\": \"2020-05-28T14:01:45.607952699Z\",\n        \"UserAgent\": \"com.atebits.Tweetie2/8.20 iOS/13.1.2 (Apple;iPhone11,8)\",\n        \"WatchTime\": 30780200760\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1PlJQmbwRDaJE\",\n        \"BroadcasterId\": \"1PXKdRnGAVYEe\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T14:03:10.875922442Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 4451307421\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1djxXQNkOaXKZ\",\n        \"BroadcasterId\": \"1PXKdRnGAVYEe\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T14:04:55.896087093Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 10013788229\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1lDxLglolpQJm\",\n        \"BroadcasterId\": \"1WgKgDZoYBXjv\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:10:41.822862798Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 11270794736\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1lDxLglolpQJm\",\n        \"BroadcasterId\": \"1WgKgDZoYBXjv\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:15:29.693216373Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 6108998055\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1RDGlQyzXMMJL\",\n        \"BroadcasterId\": \"6696493\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-28T15:19:20.071669597Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 5710079259\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1YqJDEZjkQvxV\",\n        \"BroadcasterId\": \"1WgKgDZoYBXjv\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-05-30T22:47:25.294822078Z\",\n        \"UserAgent\": \"Twitter/8.20 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 8179137429\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1jMJgQkkmjPKL\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T00:57:31.563109557Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5030197213\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1kvJpXMYowbJE\",\n        \"BroadcasterId\": \"1oNQlLnNgXkQw\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T16:27:52.634198785Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 10565530635\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OdJrqOaOyQGX\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T17:25:00.305175685Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5221652449\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OdJrqOaOyQGX\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T17:27:47.286694488Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 4457419841\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1OdJrqOaOyQGX\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-02T17:54:27.144462479Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5758937080\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1ypKdQqydXvGW\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-03T01:41:46.981614891Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 30430427519\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1kvKpXMdkwPKE\",\n        \"BroadcasterId\": \"1xkjDBadNZoQz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-03T22:14:56.677494285Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 6478084275\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1DXGyeWogDnGM\",\n        \"BroadcasterId\": \"1qLQGVryRAJEJ\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-04T00:10:48.852778237Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 7351886979\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1djGXQWYjwNJZ\",\n        \"BroadcasterId\": \"1raQZonlMGYKz\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-04T23:21:06.315825774Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 4490703695\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1MYxNklPEEXKw\",\n        \"BroadcasterId\": \"1zYKbGwnrzBje\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-05T01:28:40.929964243Z\",\n        \"UserAgent\": \"Twitter/8.21 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 10067999812\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1MYxNklPEEXKw\",\n        \"BroadcasterId\": \"1zYKbGwnrzBje\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-05T03:35:18.224299702Z\",\n        \"UserAgent\": \"Twitter/8.21 CFNetwork/1107.1 Darwin/19.0.0\",\n        \"WatchTime\": 10983359710\n      }\n    },\n    {\n      \"Chats\": [\n\n      ],\n      \"WatchSession\": {\n        \"BroadcastId\": \"1nAKEAOBYOkKL\",\n        \"BroadcasterId\": \"32378\",\n        \"NComments\": 0,\n        \"NHearts\": 0,\n        \"Start\": \"2020-06-08T17:28:55.179847183Z\",\n        \"UserAgent\": \"Twitter/8.19 CFNetwork/1121.2.2 Darwin/19.3.0\",\n        \"WatchTime\": 5860872196\n      }\n    }\n  ],\n  \"Personalization\": [\n    \"Other\"\n  ],\n  \"PurchaseRecords\": [\n\n  ],\n  \"SuperHeartsGiven\": [\n\n  ],\n  \"Superfans\": [\n\n  ],\n  \"SuperfansOf\": [\n\n  ],\n  \"TwitterBroadcasts\": [\n\n  ],\n  \"TwitterGuestBroadcasts\": [\n\n  ],\n  \"TwitterWatchedBroadcasts\": [\n\n  ],\n  \"User\": {\n    \"AppleId\": \"\",\n    \"DigitsId\": \"\",\n    \"FacebookId\": \"\",\n    \"GoogleId\": \"\",\n    \"Language\": \"\",\n    \"LastLogin\": {\n      \"Time\": \"2020-06-08T22:10:27.501587862Z\"\n    },\n    \"TimeZone\": \"\",\n    \"UserPublic\": {\n      \"Created\": {\n        \"Time\": \"2020-05-28T03:00:23.444879423Z\"\n      },\n      \"Description\": \"The new ambassador of 2020. I’m  writing a movie called -Matthew Liv’s-.   “blank page” the final revaluation before the beginning.\",\n      \"DisplayName\": \"ryan britton\",\n      \"Id\": \"1xkQDAOwbGzKz\",\n      \"NFollowers\": 0,\n      \"NFollowing\": 0,\n      \"ProfileImageURLs\": [\n        {\n          \"Height\": 128,\n          \"SSLURL\": \"https://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_reasonably_small.jpg\",\n          \"URL\": \"http://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_reasonably_small.jpg\",\n          \"Width\": 128\n        },\n        {\n          \"Height\": 200,\n          \"SSLURL\": \"https://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_200x200.jpg\",\n          \"URL\": \"http://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_200x200.jpg\",\n          \"Width\": 200\n        },\n        {\n          \"Height\": 400,\n          \"SSLURL\": \"https://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_400x400.jpg\",\n          \"URL\": \"http://pbs.twimg.com/profile_images/1268762073015648256/L39Go9Kf_400x400.jpg\",\n          \"Width\": 400\n        }\n      ],\n      \"TwitterId\": \"1265835180419399680\",\n      \"TwitterScreenName\": \"britton_ryan\",\n      \"TwitterVerified\": false,\n      \"Username\": \"britton_ryan\",\n      \"Vip\": \"\"\n    }\n  }"
