### ISSUE TITLE
Sources to learn for interview questions

### ISSUE THREAD

**Issue by raj4dev** [h5bp/Front-end-Developer-Interview-Questions#338]
I tried to find javascript books which go beyond just basic DOM manipulation and help us to answer interview questions like "Explain event delegation" (and more). I could not find any so far. Most books don't cover js in enough detail. So, can we also have a list of books to read ?

**Comment by marcobiedermann** [comment]
[You Don't Know JS](https://github.com/getify/You-Dont-Know-JS)
[O'Reilly Store](http://search.oreilly.com/?q=javascript)

O'Reilly offers a lot of great JS Books. Maybe you find something there.

**Comment by xthilakx** [comment]
@rags4developer Professional Javascript for Web Developers by Nicholas C. Zakas is a great book, it covers almost all aspects of JS. You Don't Know JS series is awesome and highly recommended as well.

**Comment by hongbinc** [comment]
This is a good source to learn JS. http://www.w3schools.com/js/

**Comment by odv** [comment]
@hongbinc  Please see http://www.w3fools.com/

**Comment by rags4developer** [comment]
probably not a good source -
https://www.google.com/search?q=w3schools%20criticism

**Comment by brianmontanaweb** [comment]
http://javascriptissexy.com/

Could there be a suggested acceptable link to an answer?

**Comment by peterasplund** [comment]
https://developer.mozilla.org/docs/Web/JavaScript

My go-to site for javascript.

**Comment by jkup** [comment]
A while ago Codeschool bought [javascript.com](javascript.com) which has a pretty good list of resources (obviously they advertise a lot of their own stuff) but you can check it out here: [https://www.javascript.com/resources](https://www.javascript.com/resources)

**Comment by yichenlivened** [comment]
I found two free courses in Udacity is very helpful. [Javascript design patterns](https://classroom.udacity.com/courses/ud989/) and [Object-Oriented Javascript](https://classroom.udacity.com/courses/ud015)

**Comment by popc0rn** [comment]
http://jstherightway.org/  - Not a book, but overall resource list, including list of good js books :)

**Comment by igregson** [comment]
Curious if folks would still recommend _JavaScript: The Good Parts_ by Crockford as a main "beyond simple DOM manipulation" read above (or along) those mentioned above. Thoughts?

**Comment by silkster** [comment]
@igregson I still recommend _The Good Parts_ to beginners in addition to more recent resources including most mentioned above since it is somewhat dated info. It still provides some well-thought-out information about why and why not to do certain things with JavaScript.

**Comment by DiJester** [comment]
aesfd

**Comment by semi-sentient** [comment]
You are better off just googling about each topic. Books do not cover every detail, but you can find multiple articles covering each question that will go into much greater detail. Of course the tricky part is sifting through good/bad articles.

I've recently done just that as I was going through and answering all of these questions on my own. Here's a site that I put up which contains a (mostly) brief answer of questions, followed by code examples and sources for further reading: http://dolem.com/#/interview/javascript

It's not complete and I'll need to revisit a few of questions, but most of the CSS and JavaScript questions contain link(s) to further explore each topic.

**Comment by thovo** [comment]
What about this gem : 
http://eloquentjavascript.net/

**Comment by minamixzy** [comment]
It's really a nice book for beginners.

2016-10-25 0:20 GMT+08:00 Tho Vo <notifications@github.com>:

**Comment by hozefaj** [comment]
Most of the times, it's better to google. SInce ES2015 and beyond the spec will keep changing, so better that way so information is current.

But for fundamentals that pretty much remain the same, http://bonsaiden.github.io/JavaScript-Garden/ is very useful.

**Comment by roblarsen** [comment]
covered in #435
