### ISSUE TITLE
HTML: What's the difference between standards mode and quirks mode?

### ISSUE THREAD

**Issue by theaemarie** [h5bp/Front-end-Developer-Interview-Questions#361]
Was just going through some of these questions, and wondered, is this item relevant now for someone who was interviewing today?

**Comment by vvscode** [comment]
@theaemarie I met some teams in last month where guys asked this question. But there they talk about projects with old codebase and enterprise applications ( which still work on IE7 - I don't know why )

**Comment by theaemarie** [comment]
Interesting. I suppose, at the very least, it is useful to know where we came from.

**Comment by matthew-dean** [comment]
I think it should be dropped. It's not worth knowing anymore, for a junior dev anyway.

**Comment by blackfalcon** [comment]
https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/430/files

:boom:

**Comment by cezaraugusto** [comment]
ok question is now removed so closing. FYI there's a good answer here https://stackoverflow.com/a/1695790/4902448
