### ISSUE TITLE
How does React's virtual DOM work?

### ISSUE THREAD

**Issue by ayxos** [h5bp/Front-end-Developer-Interview-Questions#367]
https://www.quora.com/How-does-Reacts-virtual-DOM-work

**Comment by hozefaj** [comment]
Isn't this is a library specific question(in this case `react`). Ideally in my view we should know HTML/JS/CSS concepts not specific to a library.

**Comment by strugee** [comment]
I agree with https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/367#issuecomment-292743098; however, "what is a virtual DOM" seems like a valid question to me as this is an approach that several different libraries are taking and exposes some other interesting underlying questions.

**Comment by cezaraugusto** [comment]
sorry but given we're still maintaining this questionnaire framework-agnostic and virtual DOM is not defined as a web standard, I'll set this as invalid for now and close. Anyway, thanks for the idea!
