### ISSUE TITLE
Believe it or not the question "How do you like your coffee?" might be considered to be unfairly discriminatory

### ISSUE THREAD

**Issue by autopulous** [h5bp/Front-end-Developer-Interview-Questions#369]
As benign as "how do you like your coffee?" seems - because you ask it during an interview it can be treated by the law as representing a hiring criterion... and as such, lacking a reasonable / logical argument that demonstrates anything related to the efficacy of any particular way of "liking your coffee" to job performance, there's the risk that a candidate could point to this question as a "cover" or excuse for unfair discrimination on other terms...

**Comment by autopulous** [comment]
For the record - I've never had a cup of coffee so perhaps I'm feeling a little defensive :stuck_out_tongue_closed_eyes:

**Comment by kirbdee** [comment]
Well if you look at it like that, you could take almost all of those "fun questions" as being discriminatory.

**Comment by matsieftw** [comment]
This would never actually fly in a court room and is more of a slippery slope style train of thought than something that has any kind of legal precedent. Considering how many interviews that are so reliant on "culture fit" have real (but often latent) discriminatory problems, the idea that someone would be able to bring a coffee preference question to court as an example of discrimination is pretty ludicrous.

**Comment by roblarsen** [comment]
Interesting discussion.  This is not something I would ever have even considered. Thanks.

Here's a still of Dale Cooper drinking coffee. 

![dale-cooper-coffee](https://user-images.githubusercontent.com/361421/30755364-5335b004-9f94-11e7-89ef-c9f7f9fd8009.png)
