### ISSUE TITLE
To be or not to be? 

### ISSUE THREAD

**Issue by thovo** [h5bp/Front-end-Developer-Interview-Questions#370]
This is actually my last question in my interview just about 3 weeks ago. My interviewer wrote out this sentence `2B || !2B` and asked me what is the result.

My answer: true as I considered `2B` as a variable and it would be true.
His answer: 43, consider this `0x2B || !0x2B`

What is yours ?

**Comment by Krizzu** [comment]
I wouldn't say it's a variable, as variables' names can't start with numbers.  
This one is bit tricky, as it doesn't stay what exactly is 2B.  
But his answer is legit, as JS accept HEX values.

**Comment by thovo** [comment]
At first, he just asked me the questions and didn't write out anything so I said it would be a variable but you  are right :)

**Comment by vvscode** [comment]
![https://www.dropbox.com/s/8rygox0ezvd6qom/Screenshot%202016-11-09%2019.26.05.png?dl=1](https://www.dropbox.com/s/8rygox0ezvd6qom/Screenshot%202016-11-09%2019.26.05.png?dl=1)

Strange question -- interviewer should keep in mind that situation is stressfull

**Comment by kirbdee** [comment]
if it was in the proper context with 0x, I would have said 43. but in the context you saw. I would also have said 2B is a variable and the result would be its value. BUT what should have happened more is you should have clarified on what 2B was exactly. interviewers love to put questions out there and want to see the candidate ask for clarification

**Comment by thovo** [comment]
@vvscode , you need to put 0x to make it work in the console as it is a hex number. Actually, after answered this question, 2 of my interviewers just wanted to know how I would deal with this strange question, they didn't expect me to anwser it right so they accepted it as a good solution :smile:

**Comment by Krizzu** [comment]
How did it go?

**Comment by thovo** [comment]
I got accepted and they are now my new leader and manager :smile:

**Comment by Krizzu** [comment]
Maaan, congratulations! :cake:  Aaaaand Good luck :D

**Comment by matthew-dean** [comment]
As @vvscode said, the correct answer in the context of web development is "Syntax Error".
