### ISSUE TITLE
I'm surprised that there are no SECURITY related questions. Here are a few examples.

### ISSUE THREAD

**Issue by andersonDadario** [h5bp/Front-end-Developer-Interview-Questions#373]
Quesitons regarding security are as important as any of those. Examples include:

- What is Cross-Site-Scripting (XSS), how many types of XSS are there and how do you mitigate it?
- What are the security considerations regarding a Single Page Application (SPA) framework?
- How Content-Security-Policy (CSP) changes the way you develop?
- What do you know about security headers?

And many others ...

**Comment by spxis** [comment]
Yes, these are good. If you provide both the questions and answers, I can add a Merge Request of the content for you (if you're not able to do this yourself). It's probably good to have a security section with 10 questions that could be chosen for modern interviews.

**Comment by andersonDadario** [comment]
I'm glad you like it and thanks for the fast reply.

The answers could be troublesome in terms of length. For example one common attack is the Cross-Site Request Forgery (CSRF). Here's what it is and how to mitigate: https://dadario.com.br/what-is-csrf/ -- Please notice the size of such answer.

I may add one at a time then. Do you prefer that I put them in here?

**Comment by spxis** [comment]
I'd say come up with a short, concise and memorable set of answers that
anyone should be able to memorize, in point form or using short and simple
sentences. People can suggest changes but the point is, keep things simple.
All at once is probably preferred.

**Comment by andersonDadario** [comment]
Forgive me my ignorance, but I've noticed a few things and have some questions:

1) There are no answers in this repository, only questions, right? So what's the point of providing answers instead of adding security questions first?

2) Supposing that answers are a requirement before adding questions, allow me to analyze your quote: "I'd say come up with a short, concise and memorable set of answers that anyone should be able to memorize, in point form or using short and simple sentences"

So basically the point is memorize questions and answers for interviews without really understanding the meaning of such answers? If that's the case the whole idea is part of the problem. You're only promoting memorization challenges instead of promoting the study that should be done instead. How is it really helpful? I'd love to help people to LEARN security instead of MEMORIZING answers to pass interviews. In short it looks a b.s. theater. Am I wrong? I hope I am, but doesn't look like to be the case.

**Comment by spxis** [comment]
If this repo doesn't have any answers, then they are not needed. If so, then provide them. I don't care. People learn in different ways, I agree. I'm offering my time to help, if required.

**Comment by andersonDadario** [comment]
The better answer for each question can be googled I guess, but the point is to include security questions as Cross-Site Scripting (XSS), Cross-Site Request Forgery (CSRF) remains in the Top 10 most common vulnerabilities in web applications according to OWASP.

I do appreciate your time to help, however it's important to stress how important this repository is and why we should not have answers 'easy to memorize' rather than 'easy to understand'. Lots of people grab questions from here. I believe that's more serious than ever as the amount of stars and views of this repository grows. 

If I list 10 security questions, is it enough for it to be added? I see many pull requests in stand by, so I wonder how often they're merged too.

**Comment by roblarsen** [comment]
A security section would be great. PR please!
