### ISSUE TITLE
Persian or Farsi translation

### ISSUE THREAD

**Issue by ghaseminya** [h5bp/Front-end-Developer-Interview-Questions#382]
Hi
I want to add Persian translation for this project,
how can i PR my translation?

**Comment by strugee** [comment]
@ghaseminya visit https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations. Click "create new file" in the upper-left corner. Type e.g. `Persian/README.md` into the filename box, then put your translation in the big text box.

Write a commit message and click the green button. GitHub'll help you through the rest. Good luck!

**Comment by Aakash1225** [comment]
Can I Help you to solve the issue?
