### ISSUE TITLE
Create .github folder

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Front-end-Developer-Interview-Questions#433]
With the goal of keeping the main folder lean and ~~mean~~ friendly,  I would like to see a handy .github folder created.

We've got CONTRIBUTING.md, that should be updated and moved. 

Then we'd have...
CODE_OF_CONDUCT.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
SUPPORT.md

Super fun.

**Comment by blackfalcon** [comment]
Suggested work reference https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by blackfalcon** [comment]
https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/436

**Comment by roblarsen** [comment]
closed via #436
