### ISSUE TITLE
Create a new website

### ISSUE THREAD

**Issue by cezaraugusto** [h5bp/Front-end-Developer-Interview-Questions#448]
from #435  

> While GitHub is popular, there are developers that rarely use source control at all, or just prefer another platform, so the website should be the go-to place for interview questions. Ours is kind of old and would be cool to have a better website.

I thought about [Docusaurus](https://github.com/facebook/Docusaurus) but any other tool would be great to have.

Please note that after #445 each topic should have its own dedicated page.

Things to discuss:

- which tool?
- which design?

I definitely don't have time to build this in the near future but can definitely help/guide anyone who's interested.

**Comment by roblarsen** [comment]
Same. I won't have time to take this on for a month or two, but even until then I can help clear obstacles, etc. for anyone who's interested in picking this up.

**Comment by AndrewUsher** [comment]
I'm interested in working on this. What will it be built with?

**Comment by AndrewUsher** [comment]
@cezaraugusto I'll just start working with whatever you have and go on from there.

**Comment by billyjov** [comment]
@AndrewUsher i can help by this. Just say which branch you want to use for develop or with which tasks I can help.

**Comment by GMaiolo** [comment]
@AndrewUsher @cezaraugusto I'm in as well

**Comment by mansisce** [comment]
I'm in as well for the same.

**Comment by roblarsen** [comment]
@cezaraugusto Is your branch in a place where you can share it?  Let's take a look and get this kicked off.

I think there are three basic phases:

- [ ] 1. Finalize on a tool. Hopefully this is quick.
- [ ] 2.  Update the the existing gh-pages branch to use that tool. We're three years out of date, so the sooner the better.  
- [ ] 3. Iterate on the new site with new pages and a new design

That's not granular at all. Do we need more granular tasks?

To everyone who has volunteered to help, who is interested in doing what?  If everyone is interested in doing look and feel or everyone is interested in doing automation we might have a problem :)

There's an existing, albeit barely used Gitter room if we want an open chat to work through the basics 

https://gitter.im/h5bp/Front-end-Developer-Interview-Questions

**Comment by roblarsen** [comment]
Also, THANK YOU ALL FOR OFFERING TO HELP.

**Comment by GMaiolo** [comment]
@roblarsen I'm looking at the gitter and see no answer for the branch request there. 
Is it being developed privately or wasn't even started?
About the _what_, I can fill any needed gap.

cc. @cezaraugusto & @AndrewUsher

**Comment by roblarsen** [comment]
I've created [new-site](https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/new-site)

**Comment by roblarsen** [comment]
[Docusaurus · Easy to Maintain Open Source Documentation Websites](https://docusaurus.io/)

**Comment by cezaraugusto** [comment]
sorry for the delay, busy times. Thanks @roblarsen for the initiative.

Created a branch called "website" which is almost done with the architecture goals I had in mind. Needs rebranding but what we have now is a good start for new grabs. Links work fine and the next person would need to tweak the homepage and make a full rebrand of the website.

Regarding the home page, we can discuss what to put in there once we have a PR. Rebrand could follow a similar standard of H5BP https://html5boilerplate.com/

To be able to run the website one needs to checkout this repo, then go to `website` folder with `yarn install && yarn start`. Website will open at http://localhost:3000

Current Preview:

<img width="1189" alt="screen shot 2018-02-08 at 2 11 25 am" src="https://user-images.githubusercontent.com/4672033/35955280-99debd04-0c75-11e8-96c4-41ddab954881.png">

**Comment by cezaraugusto** [comment]
regarding the above please feel free to either push a PR with what we have, ping me on this issue or DM me over Twitter (same handler). I'll be glad to help. Let's make it cool!

**Comment by billyjov** [comment]
@cezaraugusto  i saw the progress on the branch. I think some things should be done first. What can I help with when I'm working on it? css?
I think that a PR with many changes does not make any sense, right?

**Comment by cezaraugusto** [comment]
@billyjov CSS would be great. We can discuss other things once we have a PR.

I'm open for design feedback but to unblock us for now, you can clone colors defined in https://html5boilerplate.com/. Just make sure the website has a proper branding too.

**Comment by billyjov** [comment]
@cezaraugusto PR opened.

**Comment by roblarsen** [comment]
Thanks @billyjov 

@cezaraugusto I made some content changes to the home page and the about page.

**Comment by cezaraugusto** [comment]
@roblarsen thanks I'll take it from there

**Comment by roblarsen** [comment]
💯

**Comment by roblarsen** [comment]
🏗 ?

What's left to do on this?

**Comment by AlexanderDLe** [comment]
Is it still possible to contribute to this website?

**Comment by roblarsen** [comment]
@AlexanderDLe It is. This ticket has been stalled for a while now.

**Comment by cezaraugusto** [comment]
happy to say that the website is ready at https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/505. thanks for your patience on this.

**Comment by cezaraugusto** [comment]
closed by https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/505.
