### ISSUE TITLE
what questions do we want? what makes a good question?

### ISSUE THREAD

**Issue by cezaraugusto** [h5bp/Front-end-Developer-Interview-Questions#450]
related: #307, #331, #335, #361, #421, #433 

From #435 

> We should describe more fully what questions we want to be added. Plus, in this project standards, what makes a good question? Being crystal clear here reduces stale PRs and encourage more contributors. Even a small addition such as a descriptive issue/PR template is helpful.
>
> Also, I think questions regarding performance, http(s) and some front-end security best practices are valid and should be included too.

**Comment by jmilanovic** [comment]
👋https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/463

**Comment by devdil** [comment]
Questions on implementing simple widgets like stopwatch/timers or maybe a small chat window can really make the interview pleasant, challenging and interesting.

**Comment by roblarsen** [comment]
Housekeeping!
