### ISSUE TITLE
How about dividing questions by seniority?

### ISSUE THREAD

**Issue by gabrielAnzaldo** [h5bp/Front-end-Developer-Interview-Questions#459]
I think that could be a good idea grouping questions by seniority, I mean having some set for entry levels, juniors, mid levels, seniors and so on.

**Comment by SenHeng** [comment]
Probably not a good idea unless there's a clean way to agree on what defines seniority. It's too subjective and differs from company to company.

**Comment by roblarsen** [comment]
As above. One person's senior is another person's trainee.
