### ISSUE TITLE
Suggested Q: What is an example of an pseduo-element?

### ISSUE THREAD

**Issue by ghost** [h5bp/Front-end-Developer-Interview-Questions#463]
See pull request for details. https://github.com/yangshun/front-end-interview-handbook/pull/39

**Comment by cezaraugusto** [comment]
hey @jmilanovic could you make a PR with this question?

**Comment by jmilanovic** [comment]
hey @cezaraugusto, done https://github.com/h5bp/Front-end-Developer-Interview-Questions/pull/469

**Comment by roblarsen** [comment]
covered in #469
