### ISSUE TITLE
Suggested Question: How can you create custom attribute for an html element?

### ISSUE THREAD

**Issue by Oluwasetemi** [h5bp/Front-end-Developer-Interview-Questions#472]
# Issue Template

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Current status

Please describe the current status of the issue you are reporting.

*response*
I think every person who intend to write HTML or develop web pages must be able to create a custom attribute for an element

# Proposal and Expected outcome

*response*
How can you create custom attribute for an html element?

Please describe your proposal and expected outcome from proposed work.

*response*
The use of data-attribute to create data-* serves as custom variable in html apart from global or element specific attributes.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

Thanks.

**Comment by roblarsen** [comment]
Thanks! This could just be a pull request, if you're still interested in us evaluating this proposal
