### ISSUE TITLE
make the website responsive

### ISSUE THREAD

**Issue by cezaraugusto** [h5bp/Front-end-Developer-Interview-Questions#509]
Follow-up of https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/448.

At this moment the website is not responsive, would be cool if we could make it so. Website is built with http://11ty.io and the task is mostly hacking the HTML/CSS.

The main challenge I think is to make the top menu responsive. Hamburger menu sounds like a good option but developer is free to add something they think fits better.

Instructions:

* fork this repo
* `npm i` to install dependencies
* `npm start` to run the website at http://localhost:9090
* hack!

**Comment by 7ictor** [comment]
✋ I'm interested in working on this!

**Comment by jdsteinbach** [comment]
Hi @cezaraugusto - I had some free time after work and took a stab at this; happy for feedback & review. Thanks!
