### ISSUE TITLE
Dated Questions -- Needs Revising

### ISSUE THREAD

**Issue by ndugger** [h5bp/Front-end-Developer-Interview-Questions#517]
I don't have time to contribute at the moment, as I'm preparing to interview a candidate right now, but I figured I'd at least write this down.

The javascript questions lack almost everything from ES6 and beyond. It briefly mentions arrow functions, but that's it.

The CSS questions lack anything to do with flexbox and/or grid. Very important for building modern layouts.

I'm sure the other questions in other sections are lagging behind as well, but I didn't look at them yet.

**Comment by roblarsen** [comment]
Thanks, we're slowly trying to turn this battleship around. We just cleaned up a bunch of old issues and I'd like to do an editorial pass.
