### ISSUE TITLE
I changed some lines and then updated the repository. But I can't see the changes on my website. why?

### ISSUE THREAD

**Issue by sohaghasemi** [h5bp/Front-end-Developer-Interview-Questions#518]
# Issue Template

The issue tracker is the preferred channel for feedback on the project, bugs relating to the publishing infrastructure (which is still a a work-in-progress) or other discussion points. 

Note:

- *Please do not open issues or pull requests that involve including answers to any of the questions.*
- *If you have a proposal for a new question or revision of an existing question, please just open a pull request.*

**Comment by roblarsen** [comment]
I'm not sure what this issue refers to.
