### ISSUE TITLE
Add Social Media Preview Image

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Front-end-Developer-Interview-Questions#522]
reference: [Customizing your repository's social media preview](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview)

**Comment by coliff** [comment]
The repo was using the 'gold' H5BP Icon (https://avatars1.githubusercontent.com/u/1136800?s=400&v=4) for the social media preview image.

I updated the repo settings to use this screen grab of the title from the homepage:

![front-end-interview-questions](https://user-images.githubusercontent.com/1212885/58393644-75aabd00-807a-11e9-92bf-ebb9493616e9.jpg)

Take a look - if you prefer the 'gold' square one we use elsewhere for any reason we can remove it from settings.

**Comment by roblarsen** [comment]
looks good to me
