### ISSUE TITLE
🕐 The history of this project... (ie. creators, maintainers & contributors)™️

### ISSUE THREAD

**Issue by darcyclarke** [h5bp/Front-end-Developer-Interview-Questions#531]
I've recently been able to review all the work done over this last year or so on the project & just wanted to give a bit of feedback. 

Most importantly, I should say that I'm extremely impressed with the work done to maintain the repo by @roblarsen @cezaraugusto & @vvscode & don't think it would be in such good shape without all of your efforts (website looks dope 🔥👍).

That said, I am a bit sad to see that the history of this project seems to have been lost to time. 

I shared the original "list" back in [2012](http://web.archive.org/web/20120909134303/http://darcyclarke.me/development/front-end-job-interview-questions) although it has it's origins as far back as 2009 (10 years ago 😰). In my initial blog post, I make reference to the fact that many of the questions were indeed sourced from a shared doc @paulirish started with our mutual friends (whom I went on to credit). That said, they were not the sole contributors to that original list that was published & subsequently turned into this project.

You can see the specific wording/reference in the initial version of the GitHub repo [here](http://web.archive.org/web/20130607083228/https://github.com/darcyclarke/Front-end-Developer-Interview-Questions). What may also have been forgotten is that this project was given to the [H5BP](https://github.com/h5bp/) team after I decided it was best as a community project then to be owned by an individual (see announcement [here](https://twitter.com/darcy/status/540972110261522432)). 

There have been many [contributors](https://github.com/h5bp/Front-end-Developer-Interview-Questions/graphs/contributors) & [maintainers](https://github.com/orgs/h5bp/teams/frontend-interview) to this project over the years but, unfortunately, I believe the way in which the project is presenting itself these days correlates to ownership & stewardship in a fashion I don't think reflects reality (ie. the current [README](https://github.com/h5bp/Front-end-Developer-Interview-Questions#contributors) & [About page](https://h5bp.org/Front-end-Developer-Interview-Questions/about/)).

Ideally, I'd like to see all attribution removed from the `README.md`, `./src/_includes/components/footer.njk` & `./src/about.njk` in lieu of references to [contributors](https://github.com/h5bp/Front-end-Developer-Interview-Questions/graphs/contributors) & [maintainers](https://github.com/orgs/h5bp/teams/frontend-interview); Otherwise, it's best to represent the history of & all contributors accurately.

I'll be making a PR with the suggestions I think are most appropriate (based on the above) before EOD. Definitely feel free to give feedback & collaborate once that is opened.

**Comment by roblarsen** [comment]
Whatever you feel is appropriate will be appropriate as far as I'm concerned. We stepped [into a void](https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/409) to try to keep this resource alive (that was two years ago [!] and it had been mostly dormant for two years before that) so if we can join the past back up to the present in a way that aligns to your vision I'm 💯 for it.  

Unlike the way that projects normally transition, we never really had continuity with the project pre-2017. Someone just @ mentioned me and I had the keys to jump-start it.
