### ISSUE TITLE
Add Hindi Language

### ISSUE THREAD

**Issue by RanaWebD** [h5bp/Front-end-Developer-Interview-Questions#565]
# Issue Template

The issue tracker is the preferred channel for feedback on the project, bugs relating to the publishing infrastructure (which is still a a work-in-progress) or other discussion points. 

Note:

- *Please do not open issues or pull requests that involve including answers to any of the questions.*
- *If you have a proposal for a new question or revision of an existing question, please just open a pull request.*

**Comment by RanaWebD** [comment]
I did not see the Hindi language. can you please add it.

**Comment by vvscode** [comment]
@RanaWebD 
Pull request is welcome

**Comment by Aakash1225** [comment]
Can I help you to solve your issue

**Comment by roblarsen** [comment]
> Can I help you to solve your issue

Can you create a Hindi translation?

**Comment by swati-gwc** [comment]
May I contribute to this? I can translate the questions in Hindi.

**Comment by roblarsen** [comment]
👍 

That would be great!

**Comment by roblarsen** [comment]
closed via #619
