### ISSUE TITLE
Define an editorial structure/editorial guidelines

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Front-end-Developer-Interview-Questions#586]
This repo is basically prose. In most projects that are prose-based, there are editorial guidelines and human beings that serve as editors. I think it would help to clarify some of those things on this project. 

It will be a stretch to create something like a style guide, but that would be the ultimate goal.  In the interim, some words in the readme/contributing docs about creating a single editorial voice will codify that expectation. I am also anointing myself "editor" so that there's an expectation about receiving feedback on the way a question is worded.

(why me? I've interviewed hundreds of candidates on three continents, I've written [five books](https://amzn.to/2R9XyrE) and since I've inherited this repo I might as well make it enjoyable 😺)

I would be happy to have other folks with professional experience with words help out crafting a unified voice for the project and/or wordsmithing questions as they come in.

**Comment by darcyclarke** [comment]
👍🏻 Love it. A few things I'd love to keep in mind going forward (& which were tennants of this project from the outset):

* tonne should always be open, understanding, encouraging etc. (we should all want interviews to be successful)
* the questions/challenges should be learning opportunities & jumping off points for discussion (boolean questions & statements should be avoided if possible)
* no answers (everyone has their own way of interpreting & potentially communicating their understanding)

**Comment by Godstyme** [comment]
Hello roblarsen, can you review my issues so that i can work on it?

**Comment by roblarsen** [comment]
:)
