### ISSUE TITLE
Language list display incorrect ( I can try to correct this)

### ISSUE THREAD

**Issue by ganushkevychv** [h5bp/Front-end-Developer-Interview-Questions#614]
![Screenshot_2020-11-26-21-52-48-595_com android chrome](https://user-images.githubusercontent.com/46418323/100390833-fe206a00-3031-11eb-8e0c-ddca8233de8c.jpg)
The issue tracker is the preferred channel for feedback on the project, bugs relating to the publishing infrastructure (which is still a a work-in-progress) or other discussion points. 

Note:

- *Please do not open issues or pull requests that involve including answers to any of the questions.*
- *If you have a proposal for a new question or revision of an existing question, please just open a pull request.*

**Comment by roblarsen** [comment]
Testing it, it looks like the design falls apart under around 390px wide.

**Comment by CodeWithBlaze** [comment]
i want to work on this issue . i never contributed before and just want to give a try

**Comment by CodeWithBlaze** [comment]
is it mandatory to keep the column count to 3 in mobile view ??

**Comment by CodeWithBlaze** [comment]
https://drive.google.com/file/d/1Z721ZucfWxI4eher9Giwf9owiLQP_ZRw/view?usp=sharing
i made column count to 2 in mobile view . the screenshot is linked

**Comment by Anubhav-developr** [comment]
i can help solving this issue
