### ISSUE TITLE
Portuguese translation needs updating

### ISSUE THREAD

**Issue by cpvalente** [h5bp/Front-end-Developer-Interview-Questions#674]
Hi,

I have looked at the Portuguese translation, out of curiosity.
The questions seem to differ from the main english version. Am assuming this is due to the age of the translation.

Also there are some comments from the last translator on how to procceed to answer some of the questions, perhaps these should be removed to be inline with the other translations (I have only checked that it does not exist in english or spanish)

I am happy to pick this up with a Pull Request if welcome

**Comment by roblarsen** [comment]
That would be great.

**Comment by roblarsen** [comment]
closed via #678

**Comment by cpvalente** [comment]
I was under the impression that the issue had been closed. Sorry about that. Closing now
