### ISSUE TITLE
intentionally is misspelled as intentiionally

### ISSUE THREAD

**Issue by flipflopmedia** [h5bp/Front-end-Developer-Interview-Questions#691]
In the following sentence: "These questions are intentiionally written..."

**Comment by roblarsen** [comment]
That seems like a great PR for someone

**Comment by Abdullah9aleh** [comment]
G

**Comment by bhairavee23** [comment]
is this issue still open? I can tackle it

**Comment by roblarsen** [comment]
> is this issue still open? I can tackle it

🙏 Thanks!

**Comment by bhairavee23** [comment]
pulled the latest code and it seems this line has been fixed:
"These questions are intentionally written to be open-ended".

this issue can be closed it seems
