### ISSUE TITLE
Adding Dynamic programming and Data Structures questions

### ISSUE THREAD

**Issue by iamziike** [h5bp/Front-end-Developer-Interview-Questions#721]
Would it be possible to add some dynamic programming questions or data structures

eg) Implementing a Hashtable or Linked List or implementing Conway's Game of Life,
seems like recruiters ask those types of questions even if you are probably just getting hired to maintain a landing page 🤔.

**Comment by vaibhav4516** [comment]
@iamziike I think the recruiter would ask questions which are related to your job role, and as far as I know from reading some interview experiences, I don't think there was any mention of, data structures and DP. 
Also, you can read some interview experiences they will give you more clear idea. 
Thanks!
Have a Good Day!!

**Comment by mubizzy** [comment]
@iamziike  it's possible top companies like Google can ask questions related to dynamic programming and data structure just to distinguish the best from the rest.
But  bear in mind that not all companies will ask questions like that but most top companies FAANG will

Thanks
Have a Great day

**Comment by LantingHe** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by NeetuSeharawat** [comment]
...
