### ISSUE TITLE
So only question but no answer?

### ISSUE THREAD

**Issue by yufanme** [h5bp/Front-end-Developer-Interview-Questions#735]
The issue tracker is the preferred channel for feedback on the project, bugs relating to the publishing infrastructure (which is still a a work-in-progress) or other discussion points. 

Note:

- *Please do not open issues or pull requests that involve including answers to any of the questions.*
- *If you have a proposal for a new question or revision of an existing question, please just open a pull request.*

**Comment by roblarsen** [comment]
https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/11 https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/300 https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/319 https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/455 https://github.com/h5bp/Front-end-Developer-Interview-Questions/issues/615 #715
