### ISSUE TITLE
Suggestions to add some questions to the JS questions thread

### ISSUE THREAD

**Issue by JAYKALIA007** [h5bp/Front-end-Developer-Interview-Questions#798]
- There's a question on the difference between let, const, and var. I'd like to add a question on **Temporal Dead Zone** next to it.

- You also have questions on currying and closures. I'd like to add **First Class Functions** and **Callback Functions** which are kind of related to closures.

- Talking about the event loop, there's a question on task queue vs call stack. I'd like to add a question each on **Microtask queue**, **Microtask queue vs Task queue**, and **Blocking of the Main Thread**

- There's a question on promises, and when and why we need them. What I'd like to add is the **Callback Hell** and the **Inversion Of Control**  as these are the issues with callbacks that promise answers.
-----

Should I go ahead and add these?

**Comment by Bidhu1024** [comment]
I can add a few important js questions, please let me know if i can add them?

**Comment by LantingHe** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by JAYKALIA007** [comment]
Hey @LantingHe , any updates on the same?

**Comment by roblarsen** [comment]
Hi @JAYKALIA007 Feel free to create PRs for EACH of the questions you'd like to add. That way we can deal with each separately if there are issues with any of them from an editorial perspective.
