### ISSUE TITLE
Update French Translation

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Front-end-Developer-Interview-Questions#820]
https://h5bp.org/Front-end-Developer-Interview-Questions/translations/french/

It should match this:

https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/main/src/translations/_template

**Comment by laetitiaZammit** [comment]
Hi @roblarsen 👋

I took a swing at tackling the french translation issue, let me know if the PR works for you 🙂, cheers!
