### ISSUE TITLE
Update Spanish Translation

### ISSUE THREAD

**Issue by roblarsen** [h5bp/Front-end-Developer-Interview-Questions#838]
https://h5bp.org/Front-end-Developer-Interview-Questions/translations/spanish/

It should match this:

https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/main/src/translations/_template

**Comment by chunkjs** [comment]
Hello ☺️ I am looking to help out. I am a native Spanish speaker, what would be the intent of this issue? Trying to see if I can pick it up! :octocat: 

@roblarsen

**Comment by roblarsen** [comment]
@chunkjs I would like the content of https://h5bp.org/Front-end-Developer-Interview-Questions/translations/spanish/ to match the content of the English version of the site. The only difference is that the English version is multiple pages and the Spanish version is a single page. Otherwise all the questions should be the same in both versions.  Does that make sense?
